# Generated by Django 2.0.3 on 2018-10-07 21:31

from django.conf import settings
from django.db import migrations, models
import hda_privileged.models


class Migration(migrations.Migration):

    dependencies = [
        ('hda_privileged', '0003_load_states_counties_20180923_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(hda_privileged.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
