# Generated by Django 2.0.3 on 2018-10-26 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hda_privileged', '0004_auto_20181007_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percentile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.FloatField()),
                ('value', models.FloatField()),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percentiles', to='hda_privileged.Data_Set')),
            ],
        ),
    ]
