# Generated by Django 2.0.3 on 2018-11-08 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hda_privileged', '0005_percentile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_point',
            name='percentile',
        ),
        migrations.AddField(
            model_name='data_point',
            name='rank',
            field=models.FloatField(default=0, help_text='The percentile for this value fits in, ranking it among the rest of the set', validators=[django.core.validators.MinValueValidator(0, message='Percentiles cannot be less than 0')]),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1000, message='Years before 1000 C.E. are extremely unlikely...'), django.core.validators.MaxValueValidator(9999, message='If it really is later than the year 9999?')]),
        ),
    ]
