# Generated by Django 2.1.1 on 2018-11-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hda_privileged', '0006_auto_20181108_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_indicator',
            name='slug',
            field=models.SlugField(default='Test-Indicator'),
            preserve_default=False,
        ),
    ]
