# Generated by Django 2.1.5 on 2019-01-29 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hda_privileged', '0008_health_indicator_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_sets', to='hda_privileged.Health_Indicator'),
        ),
    ]
