# Generated by Django 2.1.5 on 2019-11-21 03:04

from django.db import migrations, models
from csv import DictReader

REGION_FILENAME = "./data/regions.csv"
DIVISION_FILENAME = "./data/divisions.csv"

def load_data(filename, fn):
    """
    Given a filename and a function - open the file with CSV DictReader,
    and pass each row read from the file into the function. Return a list
    of the results, i.e. map(f, rows)
    """
    with open(filename, encoding='utf-8') as csvf:
        return [fn(r) for r in DictReader(csvf)]


def make_region(region_model):
    """
    
    """
    return lambda row: region_model(
       region_num=row['REGION_NUM'],
       region_name=row['REGION_NAME']
    )

def make_division(division_model):
    """
    """
    return lambda row: division_model(
        division_num = row['DIVISION_NUM'],
        division_name = row['DIVISION_NAME']
    )


def load_regions(apps, schema_editor):
    Region = apps.get_model('hda_privileged','Region')
    regions = load_data(REGION_FILENAME, make_region(Region))

    for r in regions:
        r.save()

def load_divisions(apps, schema_editor):
    Division = apps.get_model('hda_privileged', 'Division')
    divisions = load_data(DIVISION_FILENAME, make_division(Division))

    for d in divisions:
        d.save()

class Migration(migrations.Migration):

    dependencies = [
        ('hda_privileged', '0011_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_num', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_num', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('division_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='utype',
            field=models.CharField(choices=[('AD', 'Administrator'), ('AS', 'Assistant')], default='AS', max_length=2),
        ),
	    migrations.RunPython(load_regions),
    ]
